import type { TravelCountry, TravelTrip } from '@anaybucket/travel-atlas'

export const travelCountries = [
  {
    code: 'USA',
    name: 'United States',
    coordinates: [-98.5795, 39.8283],
    status: 'lived',
    cities: [
      { id: 'sf', name: 'San Francisco', coordinates: [-122.4194, 37.7749] },
      { id: 'san-ramon', name: 'San Ramon', coordinates: [-121.978, 37.7799] },
      { id: 'san-jose', name: 'San Jose', coordinates: [-121.8863, 37.3382] },
      { id: 'la', name: 'Los Angeles', coordinates: [-118.2437, 34.0522] },
      { id: 'denver', name: 'Denver', coordinates: [-104.9903, 39.7392] },
      {
        id: 'colorado-springs',
        name: 'Colorado Springs',
        coordinates: [-104.8214, 38.8339],
      },
      { id: 'chicago', name: 'Chicago', coordinates: [-87.6298, 41.8781] },
      { id: 'champaign', name: 'Champaign', coordinates: [-88.2434, 40.1164] },
      { id: 'nyc', name: 'New York City', coordinates: [-74.006, 40.7128] },
    ],
  },
  {
    code: 'IND',
    name: 'India',
    coordinates: [78.9629, 20.5937],
    status: 'lived',
    cities: [
      { id: 'kolkata', name: 'Kolkata', coordinates: [88.3639, 22.5726] },
      { id: 'bangalore', name: 'Bangalore', coordinates: [77.5946, 12.9716] },
      { id: 'goa', name: 'Goa', coordinates: [74.124, 15.2993] },
    ],
  },
  {
    code: 'GBR',
    name: 'United Kingdom',
    coordinates: [-3.436, 55.3781],
    status: 'visited',
    visitedAt: '2023',
    cities: [{ id: 'london', name: 'London', coordinates: [-0.1276, 51.5072] }],
  },
  {
    code: 'ITA',
    name: 'Italy',
    coordinates: [12.5674, 41.8719],
    status: 'visited',
    cities: [
      { id: 'rome', name: 'Rome', coordinates: [12.4964, 41.9028] },
      { id: 'florence', name: 'Florence', coordinates: [11.2558, 43.7696] },
    ],
  },
  {
    code: 'JPN',
    name: 'Japan',
    coordinates: [138.2529, 36.2048],
    status: 'visited',
    visitedAt: '2024',
    summary: 'Dense cities, precise transit, and food worth building a trip around.',
    cities: [
      { id: 'tokyo', name: 'Tokyo', coordinates: [139.6917, 35.6895] },
      { id: 'kyoto', name: 'Kyoto', coordinates: [135.7681, 35.0116] },
      { id: 'osaka', name: 'Osaka', coordinates: [135.5023, 34.6937] },
    ],
  },
  {
    code: 'THA',
    name: 'Thailand',
    coordinates: [100.9925, 15.87],
    status: 'visited',
    cities: [
      { id: 'bangkok', name: 'Bangkok', coordinates: [100.5018, 13.7563] },
      { id: 'phuket', name: 'Phuket', coordinates: [98.3381, 7.8804] },
    ],
  },
  {
    code: 'SGP',
    name: 'Singapore',
    coordinates: [103.8198, 1.3521],
    status: 'visited',
    cities: [{ id: 'singapore', name: 'Singapore', coordinates: [103.8198, 1.3521] }],
  },
  {
    code: 'FRA',
    name: 'France',
    coordinates: [2.2137, 46.2276],
    status: 'visited',
    visitedAt: '2023',
    summary: 'Food, museums, trains, and long walks.',
    cities: [
      { id: 'paris', name: 'Paris', coordinates: [2.3522, 48.8566] },
      { id: 'nice', name: 'Nice', coordinates: [7.262, 43.7102] },
    ],
  },
  {
    code: 'MCO',
    name: 'Monaco',
    coordinates: [7.4246, 43.7384],
    status: 'visited',
    cities: [{ id: 'monaco', name: 'Monaco', coordinates: [7.4246, 43.7384] }],
  },
  {
    code: 'CHE',
    name: 'Switzerland',
    coordinates: [8.2275, 46.8182],
    status: 'visited',
    cities: [{ id: 'geneva', name: 'Geneva', coordinates: [6.1432, 46.2044] }],
  },
  {
    code: 'KOR',
    name: 'South Korea',
    coordinates: [127.7669, 35.9078],
    status: 'visited',
    cities: [{ id: 'seoul', name: 'Seoul', coordinates: [126.978, 37.5665] }],
  },
  {
    code: 'TWN',
    name: 'Taiwan',
    coordinates: [120.9605, 23.6978],
    status: 'visited',
    cities: [{ id: 'taipei', name: 'Taipei', coordinates: [121.5654, 25.033] }],
  },
  {
    code: 'PRT',
    name: 'Portugal',
    coordinates: [-8.2245, 39.3999],
    status: 'want-to-visit',
    summary: 'A future food, coast, and architecture trip.',
    cities: [
      { id: 'lisbon', name: 'Lisbon', coordinates: [-9.1393, 38.7223] },
      { id: 'porto', name: 'Porto', coordinates: [-8.6291, 41.1579] },
    ],
  },
] satisfies TravelCountry[]

export const travelTrips = [
  {
    id: 'winter-22',
    name: 'Winter 22',
    date: '2022',
    status: 'completed',
    summary: 'SF to India, with Bangalore and Goa in the middle.',
    stops: [
      { countryCode: 'USA', cityId: 'sf' },
      { countryCode: 'IND', cityId: 'kolkata' },
      { countryCode: 'IND', cityId: 'bangalore' },
      { countryCode: 'IND', cityId: 'goa' },
      { countryCode: 'IND', cityId: 'kolkata' },
    ],
  },
  {
    id: 'summer-23',
    name: 'Summer 23',
    date: '2023',
    status: 'completed',
    summary: 'A US loop through Colorado, Chicago, and New York.',
    stops: [
      { countryCode: 'USA', cityId: 'sf' },
      { countryCode: 'USA', cityId: 'denver' },
      { countryCode: 'USA', cityId: 'colorado-springs' },
      { countryCode: 'USA', cityId: 'chicago' },
      { countryCode: 'USA', cityId: 'colorado-springs' },
      { countryCode: 'USA', cityId: 'nyc' },
      { countryCode: 'USA', cityId: 'sf' },
    ],
  },
  {
    id: 'fall-24',
    name: 'Fall 24',
    date: '2024',
    status: 'completed',
    summary: 'Chicago to New York City and back.',
    stops: [
      { countryCode: 'USA', cityId: 'chicago' },
      { countryCode: 'USA', cityId: 'nyc' },
      { countryCode: 'USA', cityId: 'chicago' },
    ],
  },
  {
    id: 'thanksgiving-24',
    name: 'Thanksgiving 24',
    date: '2024',
    status: 'completed',
    summary: 'Chicago to London, then Rome.',
    stops: [
      { countryCode: 'USA', cityId: 'chicago' },
      { countryCode: 'GBR', cityId: 'london' },
      { countryCode: 'ITA', cityId: 'rome' },
    ],
  },
  {
    id: 'winter-24',
    name: 'Winter 24',
    date: '2024',
    status: 'completed',
    summary: 'San Francisco through Japan, Thailand, India, and Singapore.',
    stops: [
      { countryCode: 'USA', cityId: 'sf' },
      { countryCode: 'JPN', cityId: 'tokyo' },
      { countryCode: 'JPN', cityId: 'kyoto' },
      { countryCode: 'JPN', cityId: 'osaka' },
      { countryCode: 'THA', cityId: 'bangkok' },
      { countryCode: 'THA', cityId: 'phuket' },
      { countryCode: 'IND', cityId: 'kolkata' },
      { countryCode: 'SGP', cityId: 'singapore' },
      { countryCode: 'USA', cityId: 'sf' },
    ],
  },
  {
    id: 'spring-25',
    name: 'Spring 25',
    date: '2025',
    status: 'completed',
    summary: 'France, Monaco, Switzerland, and back through Paris.',
    stops: [
      { countryCode: 'USA', cityId: 'chicago' },
      { countryCode: 'FRA', cityId: 'paris' },
      { countryCode: 'FRA', cityId: 'nice' },
      { countryCode: 'MCO', cityId: 'monaco' },
      { countryCode: 'FRA', cityId: 'nice' },
      { countryCode: 'CHE', cityId: 'geneva' },
      { countryCode: 'FRA', cityId: 'paris' },
      { countryCode: 'USA', cityId: 'chicago' },
    ],
  },
  {
    id: 'summer-25-asia',
    name: 'Summer 25 Asia',
    date: '2025',
    status: 'completed',
    summary: 'San Francisco to Japan, Korea, back through Japan, then home.',
    stops: [
      { countryCode: 'USA', cityId: 'sf' },
      { countryCode: 'JPN', label: 'Japan' },
      { countryCode: 'KOR', label: 'Korea' },
      { countryCode: 'JPN', label: 'Japan' },
      { countryCode: 'USA', cityId: 'sf' },
    ],
  },
  {
    id: 'summer-25-us',
    name: 'Summer 25 US',
    date: '2025',
    status: 'completed',
    summary: 'San Francisco to Los Angeles to Chicago and back.',
    stops: [
      { countryCode: 'USA', cityId: 'sf' },
      { countryCode: 'USA', cityId: 'la' },
      { countryCode: 'USA', cityId: 'chicago' },
      { countryCode: 'USA', cityId: 'sf' },
    ],
  },
  {
    id: 'winter-25',
    name: 'Winter 25',
    date: '2025',
    status: 'completed',
    summary: 'San Francisco to Japan, Taiwan, then back.',
    stops: [
      { countryCode: 'USA', cityId: 'sf' },
      { countryCode: 'JPN', label: 'Japan' },
      { countryCode: 'TWN', label: 'Taiwan' },
      { countryCode: 'USA', cityId: 'sf' },
    ],
  },
] satisfies TravelTrip[]
